# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 638901c53b5e47538eb5be07ed986ea78401a53d64b7ff0ee072cb513ac15772d7a125198170160ae33f5f2ed73315775e5777d092a87fe05abb07f27ba0f443

test:
  secret_key_base: 25fea2dfcce69b3073ff5a77379303c4348e05095fe06b36e779650e866336a3285235686654ec480977ffa74d30930a565c2bea6d21379731e8fb7a7a27ecb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
